### ISSUE TITLE
Exception when resolving a combined holiday calendar in ImmutableReferenceData

### ISSUE THREAD

**Issue by jawhiting** [OpenGamma/Strata#1295]
If I create an ImmutableReferenceData instance using a pre-supplied holiday calendar, and that holiday calendar is a combined one, then a later resolve using the holiday calendar's Id (eg "Fri/Sat+Sat/Sun") will fail (because the resolver expects to just find the components and do the combining itself. There is an example unit test and stack trace below.

Now, this may be deliberate, and it is expected to create the reference data object from the basic ref data, however in this case I'm being passed a holiday calendar that was created elsewhere, and therefore don't have control over whether it is a combined one or not, and the CombinedHolidayCalendar class isn't exposed, so I can't unpack it into the constituent calendars.

    @Test
    public void testImmutableReferenceDataWithMergedHolidays() {
        HolidayCalendar hc = HolidayCalendars.FRI_SAT.combinedWith(HolidayCalendars.SAT_SUN);
        ImmutableReferenceData referenceData = ImmutableReferenceData.of(hc.getId(), hc);
        LocalDate date = BusinessDayAdjustment.of(BusinessDayConventions.PRECEDING, hc.getId()).adjust(LocalDate.of(2016, 8, 20), referenceData);
        assertEquals(LocalDate.of(2016, 8, 18), date);
    }

This exception results:

com.opengamma.strata.basics.ReferenceDataNotFoundException: Reference data not found for identifier 'Fri/Sat' of type 'HolidayCalendarId'

	at com.opengamma.strata.basics.ImmutableReferenceData.getValue(ImmutableReferenceData.java:125)
	at com.opengamma.strata.basics.date.HolidayCalendarId.lambda$null$3(HolidayCalendarId.java:96)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
	at com.opengamma.strata.basics.date.HolidayCalendarId.lambda$create$4(HolidayCalendarId.java:97)
	at com.opengamma.strata.basics.date.HolidayCalendarId.resolve(HolidayCalendarId.java:166)
	at com.opengamma.strata.basics.date.BusinessDayAdjustment.adjust(BusinessDayAdjustment.java:91)

**Comment by jodastephen** [comment]
Combination holiday calendars like this are awkward. The code does indeed expect the two calendars to be added to reference data separately. I'll see if there is anything we can do.
