### ISSUE TITLE
StandardRollConventions NONE

### ISSUE THREAD

**Issue by karin100** [OpenGamma/Strata#1385]
Hi,
In FPML the rollconvention there is a convention "NONE"
but when trying to use it I got the following:
Caused by: java.lang.IllegalArgumentException: RollConvention name not found: NONE
	at com.opengamma.strata.collect.named.ExtendedEnum.lookup(ExtendedEnum.java:314)
	at com.opengamma.strata.basics.schedule.RollConvention.of(RollConvention.java:49)
	
in the code it seems that you are referring to "None" instead of "NONE"

**Comment by jodastephen** [comment]
The FpML parser correctly parses "NONE", see `FpmlDocumentParserTest` and  `ird-ex07-ois-swap.xml`. In code, you should use the constants on `RollConventions`.
