### ISSUE TITLE
Does not build on ARM64 architecture (Jetson TX2)

### ISSUE THREAD

**Issue by vegabook** [OpenGamma/Strata#1965]
Doesn't build on my Ubuntu 16.04, Java 8, Jetson TX2 (Arm 64 bit, 8 GB RAM). Most tests pass until this:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 2994, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 134.444 s <<< FAILURE! - in TestSuite
[ERROR] adjointPriceRegression(com.opengamma.strata.pricer.impl.option.BlackBarrierPriceFormulaRepositoryTest)  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: expected [1.55632293548648] but found [1.5563229354864467]
	at com.opengamma.strata.pricer.impl.option.BlackBarrierPriceFormulaRepositoryTest.assertRelative(BlackBarrierPriceFormulaRepositoryTest.java:297)
	at com.opengamma.strata.pricer.impl.option.BlackBarrierPriceFormulaRepositoryTest.adjointPriceRegression(BlackBarrierPriceFormulaRepositoryTest.java:290)

[ERROR] regression_pv(com.opengamma.strata.pricer.capfloor.BlackIborCapletFloorletPeriodPricerTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected [3.4403901240887094] but found [3.4403901240887222]
	at com.opengamma.strata.pricer.capfloor.BlackIborCapletFloorletPeriodPricerTest.regression_pv(BlackIborCapletFloorletPeriodPricerTest.java:617)

[ERROR] three_leg_swap(com.opengamma.strata.pricer.swap.DiscountingSwapProductPricerTest)  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: expected [[EUR 0]] but found [[EUR 1.862645149230957E-9]]
	at com.opengamma.strata.pricer.swap.DiscountingSwapProductPricerTest.three_leg_swap(DiscountingSwapProductPricerTest.java:1082)

[ERROR] flatVolTest(com.opengamma.strata.pricer.impl.volatility.local.ImpliedTrinomialTreeLocalVolatilityCalculatorTest)  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError: expected [0] but found [1]
	at com.opengamma.strata.pricer.impl.volatility.local.ImpliedTrinomialTreeLocalVolatilityCalculatorTest.flatVolTest(ImpliedTrinomialTreeLocalVolatilityCalculatorTest.java:79)

[ERROR] test_explainPresentValue(com.opengamma.strata.pricer.cms.SabrExtrapolationReplicationCmsLegPricerTest)  Time elapsed: 0.195 s  <<< FAILURE!
java.lang.AssertionError: expected [39728.51321029542] but found [39728.51321029527]
	at com.opengamma.strata.pricer.cms.SabrExtrapolationReplicationCmsLegPricerTest.test_explainPresentValue(SabrExtrapolationReplicationCmsLegPricerTest.java:299)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BlackIborCapletFloorletPeriodPricerTest.regression_pv:617 expected [3.4403901240887094] but found [3.4403901240887222]
[ERROR]   SabrExtrapolationReplicationCmsLegPricerTest.test_explainPresentValue:299 expected [39728.51321029542] but found [39728.51321029527]
[ERROR]   BlackBarrierPriceFormulaRepositoryTest.adjointPriceRegression:290->assertRelative:297 expected [1.55632293548648] but found [1.5563229354864467]
[ERROR]   ImpliedTrinomialTreeLocalVolatilityCalculatorTest.flatVolTest:79 expected [0] but found [1]
[ERROR]   DiscountingSwapProductPricerTest.three_leg_swap:1082 expected [[EUR 0]] but found [[EUR 1.862645149230957E-9]]
[INFO] 
[ERROR] Tests run: 2994, Failures: 5, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Strata-Parent ...................................... SUCCESS [  5.449 s]
[INFO] Strata-Collect ..................................... SUCCESS [ 20.323 s]
[INFO] Strata-Basics ...................................... SUCCESS [ 20.294 s]
[INFO] Strata-Data ........................................ SUCCESS [  9.978 s]
[INFO] Strata-Product ..................................... SUCCESS [ 28.932 s]
[INFO] Strata-Math ........................................ SUCCESS [ 20.872 s]
[INFO] Strata-Market ...................................... SUCCESS [ 21.424 s]
[INFO] Strata-Loader ...................................... SUCCESS [ 12.806 s]
[INFO] Strata-Pricer ...................................... FAILURE [02:31 min]
[INFO] Strata-Calc ........................................ SKIPPED
[INFO] Strata-Measure ..................................... SKIPPED
[INFO] Strata-Report ...................................... SKIPPED
[INFO] Strata-Examples .................................... SKIPPED
[INFO] Strata-Root ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:53 min
[INFO] Finished at: 2019-05-11T18:39:38+01:00
[INFO] Final Memory: 44M/738M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project strata-pricer: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/nvidia/scratch/Strata/modules/pricer/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :strata-pricer
```

Any ideas?

**Comment by jodastephen** [comment]
It looks like these are floating point differences. We don't see the issue using a mixture of Macs, PCs and Linux CI servers, so I assume its the Jetson.

@cjkent previously wrote this using [Javassist](https://www.javassist.org/) to enforce `strictfp` on all Strata code. It is possible that applying this will solve your problem:

```
class StrictfpTranslator implements Translator {
  @Override
  public void start(ClassPool pool) throws NotFoundException, CannotCompileException {
  }

  @Override
  public void onLoad(ClassPool pool, String className) throws NotFoundException, CannotCompileException {
    if (className.startsWith("com.opengamma.strata")) {
      CtClass ctClass = pool.get(className);

      if (!ctClass.isInterface()) {
        addStrictfp(ctClass);
      }
    }
  }

  private static void addStrictfp(CtClass ctClass) throws NotFoundException {
    Arrays.stream(ctClass.getDeclaredMethods()).forEach(m -> m.setModifiers(m.getModifiers() | Modifier.STRICT));
    CtClass superclass = ctClass.getSuperclass();

    if (superclass != null && !superclass.getName().equals("java.lang.Object")) {
      addStrictfp(superclass);
    }
  }
}
Loader classloader = new Loader();
classloader.addTranslator(ClassPool.getDefault(), new StrictfpTranslator());
```

(where everything has to be loaded via the special classloader).

I imagine a Java agent could also be written to add `strictfp`.

**Comment by vegabook** [comment]
Will give it a try thanks. Owing to the fact that I'm quite new to strata I'm going to close for now and get back if I still have problems.
