### ISSUE TITLE
Exception when serializing ImmutableRatesProvider

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#844]
Due to `FxMatrix` not being serializable.

```
java.lang.IllegalStateException: No registered converter found: class com.opengamma.strata.basics.currency.FxMatrix
        at org.joda.convert.StringConvert.findTypedConverter(StringConvert.java:405)
        at org.joda.beans.ser.xml.JodaBeanXmlWriter.writeSimple(JodaBeanXmlWriter.java:364)
        at org.joda.beans.ser.xml.JodaBeanXmlWriter.writeBean(JodaBeanXmlWriter.java:198)
        at org.joda.beans.ser.xml.JodaBeanXmlWriter.writeToBuilder(JodaBeanXmlWriter.java:168)
        at org.joda.beans.ser.xml.JodaBeanXmlWriter.write(JodaBeanXmlWriter.java:132)
        at org.joda.beans.ser.xml.JodaBeanXmlWriter.write(JodaBeanXmlWriter.java:121)
        at com.opengamma.excel.function.gui.ObjectReveal.xml(ObjectReveal.java:73)
        at com.opengamma.excel.function.gui.ObjectReveal.lambda$serializer$44(ObjectReveal.java:59)
        at com.opengamma.excel.function.gui.ObjectSerializationView.init(ObjectSerializationView.java:32)
        at com.opengamma.excel.function.gui.ObjectSerializationView.<init>(ObjectSerializationView.java:22)
        at com.opengamma.excel.function.gui.ObjectReveal.init(ObjectReveal.java:47)
        at com.opengamma.excel.function.gui.ObjectReveal.<init>(ObjectReveal.java:27)
        at com.opengamma.excel.function.gui.GuiFunctions.lambda$revealObject$40(GuiFunctions.java:48)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by cjkent** [comment]
Note, this is about Joda bean serialization, not Java default serialization. `FxMatrix` would have to be a bean to fix this problem.

**Comment by jodastephen** [comment]
FxMatrix now serializable
